---
networks:
  inet:  { netrange: '198.51.100', prefix: '26', gateway: '1' }
  srv1:  { netrange: '10.2.1', prefix: '23', 'gateway': '254' }
  cloud: { netrange: '10.2.2', prefix: '23', 'gateway': '254' }
